---
title: "Raw Regressions"
author: "Sarah Barnes"
date: "2023-04-15"
output: html_document
---
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```
#### Install Packages
```{r echo=T, results = "hide"}
library(tidyverse)
library(tidyr)
library(plotrix)
library(cowplot)
library(reshape2)
library(RColorBrewer)
library(gridExtra)
library(knitr)
library(dplyr)
theme_set(theme_cowplot())
```

### Load master dataset 

```{r echo=T}
load("master.RData")
```

## --- PLOTS ---

## Hydroacoustics: Substrate
###   Clay
```{r}
sub_only <- subset(master, perc_clay != "NA") # to get rid of hoop nets 

clay <- ggplot(sub_only, aes(x=perc_clay, y=matureallCpue)) + 
  geom_point()+
  geom_smooth(method=lm) +
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  ylim(0,8) +
  scale_color_brewer(palette="Dark2") +
  labs(x= "% Clay (<.0005 mm)", y= "CPUE of Fecund Fish (fish/hour)", color = "Month")
clay
```

###   Sand
```{r}
sand <- ggplot(sub_only, aes(perc_sand, y=matureallCpue)) + 
  geom_point()+
  geom_smooth(method=lm) +
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  ylim(0,8) +
  scale_color_brewer(palette="Dark2") +
  labs( x= "% Sand (0.05-2 mm)", y= "CPUE of Fecund Fish (fish/hour)")
sand
```

###    Silt
```{r}
silt<- ggplot(sub_only, aes(x=perc_silt, y=matureallCpue)) + 
  geom_point()+
  geom_smooth(method=lm) +
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  ylim(0,8) +
  scale_color_brewer(palette="Dark2") +
  labs( x= "% Silt (.0005 - 0.05 mm)", y= "CPUE of Fecund Fish (fish/hour)")
silt
```

###    Rock
```{r}
rock <- ggplot(sub_only, aes(x=perc_rock, y=matureallCpue)) + 
  geom_point()+
  geom_smooth(method=lm) +
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  ylim(0,8) +
  scale_color_brewer(palette="Dark2") +
  labs( x= "% Rock (>2 mm)", y= "CPUE of Fecund Fish (fish/hour)")
rock
```

###   All Substrate
```{r, fig.dim=c(10,10)}
grid.arrange(clay, sand, silt, rock, nrow=2, ncol=2)
```

## Hydroacoustics: Vegetation
###   Vegetation Height
```{r}
sub_veg <- subset(master, avg_vegheight != "NA")

veg_height <- ggplot(sub_veg, aes(x=avg_vegheight, y=matureallCpue)) + 
  geom_point()+
  geom_smooth(method=loess, color="turquoise4") +
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  labs( x= "Average Vegetation Height (m)", y= "CPUE of Fecund Fish (fish/hour)")
veg_height
```

###   Vegetation: Cover
```{r}
veg_cover <- ggplot(sub_veg, aes(x=avg_vegcover, y=matureallCpue)) + 
  geom_point()+
  #scale_y_continuous(trans="log2") +
  geom_smooth(method=lm, color="turquoise4") +
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  labs( x= "Average Vegetation Cover (%)", y= "CPUE of Fecund Fish (fish/hour)")
veg_cover

```

### Depth
```{r}
depth_bin <- ggplot(master, aes(x=as.factor(depth_bin), y=matureallCpue)) + 
  geom_boxplot()+
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  labs( x= "Depth Bin", y= "CPUE of Fecund Fish (fish/hour)")
depth_bin
```

### Month
```{r}
month <- ggplot(master, aes(x=as.factor(month), y=matureallCpue)) + 
  geom_boxplot() +
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12, angle = 90),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  labs( x= "Month", y= "CPUE of Fecund Fish (fish/hour)")
month
```

### Date
```{r}
date <- ggplot(master, aes(x=date_time_set, y=matureallCpue)) + 
  geom_point()+
  geom_jitter() +
  geom_smooth(method=loess, color = "turquoise4", se=F)+
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12, angle = 90),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  labs( x= "Date", y= "CPUE of Fecund Fish (fish/hour)") +
  facet_wrap(~depth_bin)
date
```

### Net Type
```{r}
net_type <- ggplot(master, aes(x=net_type, y=matureallCpue)) + 
  geom_boxplot()+
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12, angle = 90),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  labs( x= "Net Type", y= "CPUE of Fecund Fish (fish/hour)")
net_type
```

### Clarity
```{r}
clarity <- ggplot(data=master, aes(x= clarity , y= matureallCpue)) + 
  geom_point()+
  #geom_smooth(method=loess) +
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  labs( x= "Water Transparency (m)", y= "CPUE of Fecund Fish (fish/hour)")
clarity
```

### Conductivity
```{r}
conduc <- ggplot(master, aes(x= conductivity , y= matureallCpue)) + 
  geom_point()+
  #geom_smooth(method=lm) +
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  labs( x= "Conductivity (mg/L)", y= "CPUE of Fecund Fish (fish/hour)")
conduc
```

### Temperature
```{r}
temp <- ggplot(master, aes(x= temp_avg , y= matureallCpue)) + 
  geom_point()+
  #geom_smooth(method=lm) +
  theme(plot.title = element_text(size=16, hjust = 0.5),
        axis.text.x = element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14)) +
  labs( x= "Average Temperature (C)", y= "CPUE of Fecund Fish (fish/hour)")
temp
```